src/Entity/Gift.php
<?php
declare(strict_types=1);

namespace App\Entity;

use App\Repository\GiftRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=GiftRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Gift
{
    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private ?\DateTimeImmutable $createdAt = null;
    /**
     * @ORM\Column(type="string", length=5000, nullable=true)
     */
    private ?string $description;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id;
    /**
     * @ORM\Column(type="float")
     */
    private ?float $price;
    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private ?\DateTimeImmutable $updatedAt = null;
    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private ?string $uuid;

    /**
     * @ORM\ManyToOne(targetEntity=Factory::class, inversedBy="gifts")
     * @ORM\JoinColumn(nullable=false)
     */
    private ?Factory $factory;

    /**
     * @ORM\ManyToOne(targetEntity=Receiver::class, inversedBy="gifts")
     */
    private ?Receiver $receiver;

    /**
     * @ORM\ManyToOne(targetEntity=GiftCode::class, inversedBy="gifts")
     * @ORM\JoinColumn(nullable=false)
     */
    private ?GiftCode $code;


    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getUuid(): ?string
    {
        return $this->uuid;
    }

    public function setUuid(string $uuid): self
    {
        $this->uuid = $uuid;

        return $this;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function updatedTimestamps(): void
    {
        $this->setUpdatedAt(new \DateTimeImmutable());
        if ($this->getCreatedAt() === null) {
            $this->setCreatedAt(new \DateTimeImmutable());
        }
    }

    public function getFactory(): ?Factory
    {
        return $this->factory;
    }

    public function setFactory(?Factory $factory): self
    {
        $this->factory = $factory;

        return $this;
    }

    public function getReceiver(): ?Receiver
    {
        return $this->receiver;
    }

    public function setReceiver(?Receiver $receiver): self
    {
        $this->receiver = $receiver;

        return $this;
    }

    public function getCode(): ?GiftCode
    {
        return $this->code;
    }

    public function setCode(?GiftCode $code): self
    {
        $this->code = $code;

        return $this;
    }

}

src/Entity/Receiver.php
<?php
declare(strict_types=1);

namespace App\Entity;

use App\Repository\ReceiverRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JetBrains\PhpStorm\Pure;

/**
 * @ORM\Entity(repositoryClass=ReceiverRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Receiver
{
    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $country;
    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private ?DateTimeImmutable $createdAt = null;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $firstName;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $lastName;
    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private ?DateTimeImmutable $updatedAt = null;
    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private ?string $uuid;

    /**
     * @ORM\OneToMany(targetEntity=Gift::class, mappedBy="receiver")
     */
    private $gifts;

    #[Pure] public function __construct()
    {
        $this->gifts = new ArrayCollection();
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = ucfirst($firstName);

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = ucfirst($lastName);

        return $this;
    }

    public function getUpdatedAt(): ?DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getUuid(): ?string
    {
        return $this->uuid;
    }

    public function setUuid(string $uuid): self
    {
        $this->uuid = $uuid;

        return $this;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function updatedTimestamps(): void
    {
        $this->setUpdatedAt(new DateTimeImmutable());
        if ($this->getCreatedAt() === null) {
            $this->setCreatedAt(new DateTimeImmutable());
        }
    }

    /**
     * @return Collection|Gift[]
     */
    public function getGifts(): Collection
    {
        return $this->gifts;
    }

    public function addGift(Gift $gift): self
    {
        if (!$this->gifts->contains($gift)) {
            $this->gifts[] = $gift;
            $gift->setReceiver($this);
        }

        return $this;
    }

    public function removeGift(Gift $gift): self
    {
        // set the owning side to null (unless already changed)
        if ($this->gifts->removeElement($gift) && $gift->getReceiver() === $this) {
            $gift->setReceiver(null);
        }

        return $this;
    }

    public function getFullName(): string
    {
        return $this->lastName . ' ' . $this->firstName;
    }
}

src/Controller/GiftController.php
<?php
declare(strict_types=1);

namespace App\Controller;

use App\Repository\FactoryRepository;
use App\Repository\GiftCodeRepository;
use App\Repository\GiftRepository;
use App\Repository\ReceiverRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/gift', name: 'gift_')]
class GiftController extends AbstractController
{
    #[Route('/home', name: 'home')]
    public function index(
        Request            $request,
        GiftRepository     $giftRepository,
        GiftCodeRepository $giftCodeRepository,
        FactoryRepository  $factoryRepository,
        ReceiverRepository $receiverRepository
    ): Response
    {

        $factories = $factoryRepository->findAll();
        $receivers = $receiverRepository->findAll();
        $codes = $giftCodeRepository->findAll();
        $gifts = $giftRepository->filter($request);

        $selected = [
            'code' => $request->get('code'),
            'factory' => $request->get('factory'),
            'receiver' => $request->get('receiver'),
            'price-min' => $request->get('price-min'),
            'price-max' => $request->get('price-max'),
        ];

        return $this->render('gift/index.html.twig', compact(
            'gifts',
            'codes',
            'receivers',
            'factories',
            'selected'
        ));
    }
}

templates/gift/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello GiftController!{% endblock %}

{% block body %}
    <div class="row mb-3 mt-3">
        <form action="" method="post">
            <div class="row">
                <div class="col-1 text-center">
                    <label for="code-input">Code</label>
                </div>
                <div class="col-1">
                    <select name="code" id="code-input" class="form-control">
                        <option value="">----</option>
                        {% for code in codes %}
                            <option value="{{ code.id }}" {{ selected.code == code.id ? 'selected' }}>{{ code.code }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-1 text-center">
                    <label for="factory-input">Factory</label>
                </div>
                <div class="col-1">
                    <select name="factory" id="factory-input" class="form-control">
                        <option value="">----</option>
                        {% for factory in factories %}
                            <option value="{{ factory.id }}" {{ selected.factory == factory.id ? 'selected' }}>{{ factory.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-1 text-center">
                    <label for="receiver-input">Receiver</label>
                </div>
                <div class="col-2">
                    <input type="text" name="receiver" id="receiver-input" class="form-control" value="{{ selected.receiver }}">
                </div>
                <div class="col-1 text-center">
                    <label for="price-input-min">Price</label>
                </div>
                <div class="col-1">
                    <input type="number" name="price-min" id="price-input-min" class="form-control" value="{{ selected['price-min'] }}">
                </div>
                <div class="col-1 text-center">
                    <label for="price-input-max">to</label>
                </div>
                <div class="col-1">
                    <input type="number" name="price-max" id="price-input-max" class="form-control" value="{{ selected['price-max'] }}">
                </div>
                <div class="col-1">
                    <input type="submit" value="Search" class="btn btn-success">
                </div>
            </div>
        </form>
    </div>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Factory</th>
            <th>receiver</th>
            <th>Price</th>
            <th>Code</th>
            <th>Description</th>
        </tr>
        </thead>
        <tbody>
        {% for gift in gifts %}
            <tr>
                <td>{{ gift.factory.name }}</td>
                <td>{{ gift.receiver ? gift.receiver.fullName }}</td>
                <td>{{ gift.price }}</td>
                <td>{{ gift.code.code }}</td>
                <td>{{ gift.description|raw }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>




{% endblock %}